#!C:\Users\madhumita\Documents\Visual Studio 2015\Projects\Project1\Project1\env\Scripts\python.exe

print("""
The 'bokeh-server' command from versions 0.10 and earlier no longer exists.
Please see the documentation for the new 'bokeh' command here:

  http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html
""")
